[build-system]
requires = ["setuptools>=82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "avaintegration_metapackage"
version = "6.0.8.40"
description = "Meta-pacote para projetos Django"
readme = "README.md"
license = { file = "LICENSE.md" }
authors = [{ name = "IFRN - DEAD", email = "dead.zl@ifrn.edu.br" }]
requires-python = ">=3.14"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    # Core
    "Django==6.0.8",
    "django-extensions==4.1",

    # KelsonCM
    "sc4py==1.1.9",
    "sc4net==1.2.0",
    "pyfwf==1.0.4",
    "abrasileirado==1.0.1",
    "django-rule-engine==1.0.1",
    "django-suap-auth==1.8.5",
    "django-sabia-auth==1.1.0",
    "django-dsgovbr==5.2.4",
    # "django-admintheme-adminlte3",
    # "django-abrasileirado",
    # Models
    "django-better-choices==3.1",
    "django-safedelete==1.5.0",
    # Rule engine
    "jsonschema==4.26.0",
    # REST
    "requests==2.34.2",
    "django-ninja==1.7.0",
    # Cache and Session
    "django-valkey==0.4.1",
    "valkey==6.1.1",
    # # Security
    # "cryptography==48.0.0",
    "pyjwt==2.13.0",
    # Audit
    "django-simple-history==3.13.0",
    # UI
    "whitenoise==6.12.0",
    "django-import-export==4.4.1",
    "django-json-widget==2.1.1",
    "django-admin-autocomplete-filter==0.7.1",
    "django-richtextfield==1.6.2",
    # Database
    "psycopg[binary,pool]==3.3.4",
    # # Image
    # "pillow==12.2.0",
    # Production
    "httpie==3.2.4",
    "sentry-sdk[django,rq]==2.68.1",
    "uvicorn==0.52.4",
    "gunicorn==26.2.0",
]


[project.optional-dependencies]
dev = [
    "pre-commit>=4.6.0",
    "black>=26.5.1",
    "ruff>=0.15.11",
    "doc8>=2.0.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.2.2",
    "pytest-coverage-gate>=1.0.3",
    "pytest-django>=4.12.0",
    "responses>=0.26.0",
]


[project.urls]
Homepage = "https://github.com/cte-zl-ifrn/integration-avaintegration_metapackage"
Source = "https://github.com/cte-zl-ifrn/integration-avaintegration_metapackage"
"Bug Tracker" = "https://github.com/cte-zl-ifrn/integration-avaintegration_metapackage/issues"
Download = "https://github.com/cte-zl-ifrn/integration-avaintegration_metapackage/releases/"
Docs = "https://cte-zl-ifrn.github.io/integration-avaintegration_metapackage/"

[tool.setuptools.packages.find]
where = ["."]
include = ["avaintegration_metapackage"]

[tool.coverage.run]
source = ["avaintegration_metapackage"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I", "S"]

[tool.black]
line-length = 120
